name: Swing Bot

on:
  schedule:
    - cron: "*/30 * * * *"  # כל חצי שעה
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: pip install requests beautifulsoup4
    - name: Run bot
      run: python main.py