name: Run Swing Bot

on:
  schedule:
    - cron: "*/30 * * * *"  # כל חצי שעה
  workflow_dispatch:  # אפשרות להרצה ידנית

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run bot
        run: python bot.py
